### PR TITLE
File enhancements

### PR DESCRIPTION
**Pull request by ldesiqueira**

### CODE REVIEW

**Comment by lovingvalerie** [comment]
I will not be accepting these changes due to the fact that I have no idea what that statement does and for all I know you could be hacking my shit.  But I still think you're handsome.

**Comment by ldesiqueira** [comment]
Just trust me, I'm not trying to hack your shit.  I also know I am handsome so there.

**Comment by lovingvalerie** [comment]
Why don't you make sure the first line stays as is and I will accept it

**Comment by ldesiqueira** [comment]
Just accept my shit its only a test

**Comment by lovingvalerie** [comment]
IDC!

**Comment by ldesiqueira** [comment]
DIAF

**Pull request merged**
